### ISSUE TITLE
Accuweather API

### ISSUE THREAD

**Issue by DavidBuchanan314** [notmyst33d/notmyst33d#1]
Hi, I also had a look inside the accuweather APK :)

I'm currently trying to figure out how to actually make API requests, but even seemingly simple ones give me an `Api Authorization failed` response (despite me passing the apikey). Do you have any examples that work?

I also tried setting my useragent to `AccuWeather AccuKotlinSDK Web Request Client/1.0`, to no avail.

Next I'm going to try MitMing the traffic.

**Comment by notmyst33d** [comment]
Hmm, Accuweather API key still works for me, maybe you are using wrong API key?
![Untitled](https://user-images.githubusercontent.com/83029360/129866335-6c8c74b6-6c71-499d-b978-73d30ab968c5.png)

**Comment by notmyst33d** [comment]
Ah, i think you are using public Accuweather API, this key only works with Enterprise API.
You can find docs for it here: http://apidev.accuweather.com/developers

**Comment by DavidBuchanan314** [comment]
That works, thanks!

I'm not sure what I was doing wrong before...
